version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: weekly
          day: sunday
          time: '07:00'
          timezone: Israel
      open-pull-requests-limit: 5
      reviewers:
          - pgilad
