env:
    browser: true
    commonjs: true
    node: true
    mocha: true
    es6: true
extends: 'eslint:recommended'
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
        - avoidEscape: true
    semi:
        - error
        - always
    prefer-const: 2
    no-var: 2
